[build]
base = "playground"
publish = "playground/dist"
command = """\
  wget -nv https://github.com/tinygo-org/tinygo/releases/download/v0.35.0/tinygo_0.35.0_amd64.deb && \
  dpkg -x tinygo_0.35.0_amd64.deb /usr/local/bin && \
  export PATH=$PATH:/usr/local/bin && \
  bun run build \
  """